title: cactuzhead
description: the spiky headed one
remote_theme: just-the-docs/just-the-docs

url: https://cactuzhead.github.io/Advanced-Progress-Bars/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
