title: cactuzhead
description: the spiky headed one
theme: just-the-docs

url: https://cactuzhead.github.io/cactuzhead

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
