title: cactuzhead
logo: docs/assets/cactuzhead avatar.png
description: the spiky headed one
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
css: _layouts/assets/css/style.css
