title: cactuzhead
description: the spiky headed one
remote_theme: just-the-docs/just-the-docs
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-remote-theme
exclude:
  - ../README.md
  - ../Gemfile
  - ../Gemfile.lock
sass:
  sass_dir: _sass
  style: compressed
  
url: https://cactuzhead.github.io/Advanced-Progress-Bars/docs/

aux_links:
  APB Repository: https://github.com/cactuzhead/Advanced-Progress-Bars

just_the_docs:
  label:
    grey:
      title: Grey Label
      color: grey
