title: cactuzhead
description: the spiky headed one
remote_theme: just-the-docs/just-the-docs@v0.8.2
plugins:
  - jekyll-remote-theme
exclude:
  - ../README.md
  - ../Gemfile
  - ../Gemfile.lock

url: https://cactuzhead.github.io/Advanced-Progress-Bars/docs/

aux_links:
  APB Repository: https://github.com/cactuzhead/Advanced-Progress-Bars

just_the_docs:
  label:
    grey:
      title: Grey Label
      color: grey
