# source 'https://rubygems.org'
# gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`
# remote_theme: just-the-docs/just-the-docs

source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "jekyll-remote-theme"
